### PR TITLE
fix last step is not executed

### PR DESCRIPTION
**Pull request by rayandrew**
If we have 730 steps, DLIO benchmark only executes until 729

The bug also persists when user specified `total_training_steps`

Fix: #235

### CODE REVIEW

**Review by hariharan-devarajan — APPROVED** [review]
Looks good

**Comment by rayandrew** [comment]
There is one bug. if `total_training_steps` is not specified, the default will be -1.
I added  check for that as well

**Review by hariharan-devarajan — CHANGES_REQUESTED** [review]
The CI is failing. Can u run pytest and check.

**Comment by rayandrew** [comment]
I think the last commit fixed the CI @hariharan-devarajan

**Review by hariharan-devarajan — APPROVED** [review]
The changes look good. 
1. We make sure we complete the step correctlyly.
2. For DALI, we need to handle the stop iteration gracefully.

**Comment by hariharan-devarajan** [comment]
@zhenghh04 This is ready for merge as well.

**Review by zhenghh04 — APPROVED** [review]

**Pull request merged**
